name: water_bottle_shop
description: A Flutter water bottle shopping app.
version: 1.0.0

environment:
  sdk: '^3.7.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
